module.exports = {
  apps: [
    {
      name: 'webintel-api',
      script: 'dist/index.js',
      cwd: '.',
      instances: 'max',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: { NODE_ENV: 'production', PORT: 3456 },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
    },
    {
      name: 'webintel-py',
      script: 'start.sh',
      interpreter: 'bash',
      cwd: './python',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: './logs/py-error.log',
      out_file: './logs/py-out.log',
    },
    {
      name: 'webintel-worker-crawl',
      script: 'dist/queue/workers/crawlWorker.js',
      cwd: '.',
      instances: 1,
      autorestart: true,
      error_file: './logs/worker-crawl-error.log',
      out_file: './logs/worker-crawl-out.log',
    },
    {
      name: 'webintel-worker-intel',
      script: 'dist/queue/workers/intelWorker.js',
      cwd: '.',
      instances: 1,
      autorestart: true,
      error_file: './logs/worker-intel-error.log',
      out_file: './logs/worker-intel-out.log',
    },
    {
      name: 'webintel-worker-monitor',
      script: 'dist/queue/workers/monitorWorker.js',
      cwd: '.',
      instances: 1,
      autorestart: true,
      error_file: './logs/worker-monitor-error.log',
      out_file: './logs/worker-monitor-out.log',
    },
    {
      name: 'webintel-dashboard',
      script: 'node_modules/.bin/next',
      args: 'start -p 3457',
      cwd: './dashboard',
      autorestart: true,
      error_file: './logs/dashboard-error.log',
      out_file: './logs/dashboard-out.log',
    },
  ],
};
