'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useSupabase } from '@/components/SupabaseProvider';
import ReportCard from '@/components/ReportCard';
import { FileText, RefreshCw } from 'lucide-react';

type Report = {
  id: string;
  title: string;
  type: string;
  date: string;
  data: Record<string, any>;
};

function generateMockReports(): Report[] {
  return [
    {
      id: 'r1',
      title: 'Competitive Landscape — May 2026',
      type: 'market-map',
      date: '2026-05-28',
      data: { competitors: ['Competitor A', 'Competitor B', 'Competitor C'], marketShare: { 'Competitor A': 35, 'Competitor B': 28, 'Competitor C': 20, Others: 17 }, trends: ['AI adoption increasing', 'Pricing pressure in enterprise tier'] },
    },
    {
      id: 'r2',
      title: 'Competitor A Battle Card',
      type: 'battle-card',
      date: '2026-05-25',
      data: { competitor: 'Competitor A', strengths: ['Brand recognition', 'Enterprise features'], weaknesses: ['Higher pricing', 'Slow support'], positioning: 'Best for mid-market companies needing fast deployment' },
    },
    {
      id: 'r3',
      title: 'Weekly Intel Brief — Week 22',
      type: 'brief',
      date: '2026-05-22',
      data: { summary: 'Three competitors updated pricing this week', highlights: ['Competitor A launched new tier', 'Competitor B redesigned homepage', 'Competitor C hired new CRO'], recommendations: ['Update battle cards', 'Prepare pricing response'] },
    },
  ];
}

export default function ReportsPage() {
  const router = useRouter();
  const { user, isLoading } = useSupabase();
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);

  useEffect(() => {
    if (!isLoading && !user) router.replace('/login');
    if (user) {
      setReports(generateMockReports());
      setLoading(false);
    }
  }, [user, isLoading, router]);

  const handleDownload = (reportId: string) => {
    const report = reports.find((r) => r.id === reportId);
    if (!report) return;
    const blob = new Blob([JSON.stringify(report.data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.title.replace(/\s+/g, '-').toLowerCase()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = (reportId: string) => {
    const report = reports.find((r) => r.id === reportId);
    if (!report) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`<html><head><title>${report.title}</title><style>body{font-family:sans-serif;padding:40px;max-width:800px;margin:auto}pre{background:#f5f5f5;padding:16px;border-radius:8px;overflow:auto}</style></head><body><h1>${report.title}</h1><p>${report.type} — ${report.date}</p><pre>${JSON.stringify(report.data, null, 2)}</pre></body></html>`);
    win.document.close();
    win.print();
  };

  if (isLoading || !user) return null;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-xl font-bold">Reports</h1>
        <button
          onClick={() => setReports(generateMockReports())}
          className="flex items-center gap-2 text-sm text-gray-600 border px-3 py-1.5 rounded-lg hover:bg-gray-50 transition-colors"
        >
          <RefreshCw className="w-4 h-4" /> Refresh
        </button>
      </div>

      {loading ? (
        <div className="bg-white rounded-xl border p-8 text-center text-sm text-gray-400">Loading reports...</div>
      ) : reports.length === 0 ? (
        <div className="bg-white rounded-xl border p-12 text-center">
          <FileText className="w-12 h-12 text-gray-300 mx-auto mb-3" />
          <h3 className="font-medium mb-1">No reports yet</h3>
          <p className="text-sm text-gray-400">Reports will appear here once generated by your monitors.</p>
        </div>
      ) : (
        <div className="grid md:grid-cols-2 gap-4">
          {reports.map((report) => (
            <ReportCard
              key={report.id}
              report={report}
              onDownload={handleDownload}
              onDownloadPDF={handleDownloadPDF}
              onView={() => setSelectedReport(selectedReport?.id === report.id ? null : report)}
              isExpanded={selectedReport?.id === report.id}
            />
          ))}
        </div>
      )}

      {selectedReport && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={() => setSelectedReport(null)}>
          <div className="bg-white rounded-xl max-w-2xl w-full max-h-[80vh] overflow-auto p-6" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-bold text-lg">{selectedReport.title}</h2>
              <button onClick={() => setSelectedReport(null)} className="text-gray-400 hover:text-gray-600 text-xl">&times;</button>
            </div>
            <pre className="bg-gray-50 rounded-lg p-4 text-xs overflow-auto">{JSON.stringify(selectedReport.data, null, 2)}</pre>
            <div className="flex gap-3 mt-4">
              <button
                onClick={() => handleDownload(selectedReport.id)}
                className="bg-gray-900 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-800 transition-colors"
              >
                Download JSON
              </button>
              <button
                onClick={() => handleDownloadPDF(selectedReport.id)}
                className="border px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors"
              >
                Download PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
